[package]
name = "oxide-kernel"
version = "0.1.0"
edition = "2024"

[features]
default = ["standalone"]
standalone = []

[lib]
crate-type = ["rlib"]
test = false
bench = false

[dependencies]
oxide-abi = { path = "../abi" }